import type { AppProps } from "next/app"
import { Provider } from "react-redux"
import { store } from "src/store/store"
import { Layout } from "src/components/Layout/Layout"
import "src/styles/globals.scss"
import "src/styles/reset.scss"
import Head from "next/head"

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Head>
        <title>Game Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </Provider>
  )
}

export default MyApp
