import type { NextPage } from "next"
import Head from "next/head"

import styles from "src/styles/pages/Cart.module.scss"
import { useState, useEffect } from "react"
import Transition from "src/components/Transition"

const Cart: NextPage = () => {
  // const [games, setGames] = useCycle(arrObj)

  return (
    <div>
      <Head>
        <title>Game Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.arr}></div>
    </div>
  )
}

export default Cart
